### ISSUE TITLE
Plugin won't stay active

### ISSUE THREAD

**Issue by slugdugg** [Ebonsignori/obsidian-at-symbol-linking#13] opened 2023-09-14 01:07 UTC
As of yesterday the @ Symbol Linking plugin wont stay enabled.  Setting and exiting, then reentering settings and it shows not enabled.  Even exiting app after setting it to enabled and you come back and it may show enabled, but doesn't do anything... and going back in to settings it will again show as disabled.

Obsidian 1.4.12 on Win11
Most recent update of @ Symbol plugin installed.

Thanks!

**Comment by Ebonsignori** [comment] 2023-09-15 06:17
Interesting, could certainly be caused by the latest change that unloads & reloads the plugin when you exit the plugin's settings page.

I can't recreate on my Mac, I'll have to pull out the Windows PC this weekend and dig into it.

Thanks for repotting this, hopefully I'll have it solved by Sunday

**Comment by luckman212** [comment] 2023-09-28 19:29
I'm seeing the same thing..

I'm on a Mac, running OS 14.0 + Obsidian 1.4.14

**Comment by Fusion** [comment] 2023-10-08 05:26
+1 same configuration as @luckman212

**Comment by Ebonsignori** [comment] 2023-10-27 22:23
Hi y'all thanks for reporting. This is hopefully fixed in https://github.com/Ebonsignori/obsidian-at-symbol-linking/releases/tag/1.4.7

**Closed by Ebonsignori** 2023-10-27 22:23 UTC
